workflows:
  ios_build:
    name: Build iOS IPA from Swift code
    environment:
      xcode: 16.4
      vars:
        APP_NAME: WalletApp
    scripts:
      - name: Check Swift version
        script: swift --version

      - name: Create Xcode project if missing
        script: |
          if [ ! -d "${APP_NAME}.xcodeproj" ]; then
            echo "No .xcodeproj found — creating one..."
            swift package init --type executable
            swift package generate-xcodeproj
          fi

      - name: Build iOS archive
        script: |
          xcodebuild -project ${APP_NAME}.xcodeproj \
            -scheme ${APP_NAME} \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            -archivePath build/${APP_NAME}.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Export IPA
        script: |
          mkdir -p build/ipa
          xcodebuild -exportArchive \
            -archivePath build/${APP_NAME}.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>method</key><string>ad-hoc</string></dict></plist>')
    artifacts:
      - build/ipa/*.ipa
