workflows:
  ios_build:
    name: Build iOS Swift App (No Mac Needed)
    environment:
      xcode: latest
      vars:
        APP_NAME: "WalletApp"
    scripts:
      - name: Create Swift project
        script: |
          mkdir -p $APP_NAME
          cd $APP_NAME
          echo 'import SwiftUI
          @main
          struct WalletApp: App {
              var body: some Scene {
                  WindowGroup {
                      Text("Hello Wallet App!")
                  }
              }
          }' > WalletApp.swift
          cd ..
      - name: Generate Xcode project
        script: |
          cd $APP_NAME
          swift package init --type executable
          rm Package.swift  # Supprime le fichier de configuration qui posait erreur
          cd ..
      - name: Build iOS app
        script: |
          xcodebuild -project $APP_NAME.xcodeproj \
          -scheme $APP_NAME \
          -destination 'generic/platform=iOS' \
          -configuration Release build
      - name: Archive app
        script: |
          xcodebuild -project $APP_NAME.xcodeproj \
          -scheme $APP_NAME \
          -destination 'generic/platform=iOS' \
          -configuration Release \
          -archivePath build/$APP_NAME.xcarchive archive
      - name: Export IPA
        script: |
          mkdir -p export
          xcodebuild -exportArchive \
            -archivePath build/$APP_NAME.xcarchive \
            -exportPath export \
            -exportOptionsPlist <(cat <<-EOF
            {
              "method": "development",
              "signingStyle": "automatic",
              "compileBitcode": false
            }
          EOF
          )
    artifacts:
      - export/*.ipa
