workflows:
  ios_build:
    name: iOS Build
    environment:
      xcode: 16.4
      vars:
        XCODE_WORKSPACE: "WalletApp.xcodeproj"
        XCODE_SCHEME: "WalletApp"
    scripts:
      - name: Clean and prepare project
        script: |
          echo "Cleaning build folders..."
          rm -rf ~/Library/Developer/Xcode/DerivedData
          echo "Removing Package.swift to prevent SwiftPM compile error"
          find . -name "Package.swift" -delete
      - name: Build for iOS
        script: |
          xcodebuild -scheme WalletApp \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            -archivePath build/WalletApp.xcarchive archive
      - name: Export IPA
        script: |
          mkdir -p export
          xcodebuild -exportArchive \
            -archivePath build/WalletApp.xcarchive \
            -exportPath export \
            -exportOptionsPlist <(cat <<-EOF
            {
              "method": "development",
              "signingStyle": "automatic",
              "teamID": "YOUR_TEAM_ID_HERE"
            }
          EOF
          )
    artifacts:
      - export/*.ipa
