workflows:
  ios_build:
    name: Build iOS Swift App (auto create project)
    environment:
      xcode: latest
      vars:
        APP_NAME: "WalletApp"
    scripts:
      - name: Create Swift project folder
        script: |
          mkdir -p $APP_NAME
          cd $APP_NAME
          echo 'import SwiftUI
          @main
          struct WalletApp: App {
              var body: some Scene {
                  WindowGroup {
                      Text("Hello Wallet App from Codemagic!")
                  }
              }
          }' > ContentView.swift
          cd ..
      - name: Create minimal Xcode project
        script: |
          mkdir -p $APP_NAME
          cd $APP_NAME
          cat > project.pbxproj <<EOF
          // !$*UTF8*$!
          {
              archiveVersion = 1;
              objectVersion = 52;
              rootObject = 1;
              objects = {};
          }
          EOF
          mkdir -p WalletApp.xcodeproj
          mv project.pbxproj WalletApp.xcodeproj/
          cd ..
      - name: Build iOS app
        script: |
          xcodebuild -project $APP_NAME/WalletApp.xcodeproj \
          -scheme WalletApp \
          -destination 'generic/platform=iOS' \
          -configuration Release build || echo "⚠️ fake build step - placeholder"
      - name: Archive app
        script: |
          mkdir -p build
          touch build/$APP_NAME.xcarchive
      - name: Export fake IPA (demo only)
        script: |
          mkdir -p export
          zip -r export/$APP_NAME.ipa $APP_NAME
    artifacts:
      - export/*.ipa
