workflows:
  ios_build:
    name: Build Real iOS App
    environment:
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "WalletApp"
    scripts:
      - name: Create SwiftUI project
        script: |
          mkdir -p $APP_NAME
          cd $APP_NAME
          cat > ContentView.swift <<'EOF'
          import SwiftUI
          @main
          struct WalletApp: App {
              var body: some Scene {
                  WindowGroup {
                      Text("Hello Wallet App!")
                  }
              }
          }
          EOF
          cd ..
      - name: Initialize Xcode project
        script: |
          cd $APP_NAME
          swift package init --type executable
          swift build
          cd ..
      - name: Build for iOS
        script: |
          xcodebuild -scheme WalletApp \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            -archivePath build/WalletApp.xcarchive archive
      - name: Export IPA
        script: |
          mkdir -p export
          xcodebuild -exportArchive \
            -archivePath build/WalletApp.xcarchive \
            -exportPath export \
            -exportOptionsPlist <(cat <<-EOF
            {
              "method": "development",
              "signingStyle": "automatic",
              "teamID": "YOUR_TEAM_ID_HERE"
            }
          EOF
          )
    artifacts:
      - export/*.ipa
