workflows:
  ios_build:
    name: Build iOS Swift App
    environment:
      xcode: latest
      vars:
        APP_NAME: "WalletApp"
    scripts:
      - name: Create Xcode project
        script: |
          mkdir -p $APP_NAME
          cd $APP_NAME
          swift package init --type executable
          cat > ContentView.swift <<'EOF'
          import SwiftUI
          @main
          struct WalletApp: App {
              var body: some Scene {
                  WindowGroup {
                      Text("Hello Wallet App!")
                  }
              }
          }
          EOF
          cd ..
          xcodebuild -scheme $APP_NAME -destination 'generic/platform=iOS' -configuration Release build
      - name: Archive app
        script: |
          xcodebuild -scheme $APP_NAME \
          -destination 'generic/platform=iOS' \
          -configuration Release \
          -archivePath build/$APP_NAME.xcarchive archive
      - name: Export IPA
        script: |
          mkdir -p export
          xcodebuild -exportArchive \
            -archivePath build/$APP_NAME.xcarchive \
            -exportPath export \
            -exportOptionsPlist <(cat <<-EOF
            {
              "method": "development",
              "signingStyle": "automatic",
              "compileBitcode": false
            }
          EOF
          )
    artifacts:
      - export/*.ipa
