workflows:
  ios-workflow:
    name: Build iOS App
    max_build_duration: 60
    environment:
      vars:
        APP_NAME: WalletApp
      flutter: none
    scripts:
      - name: Install dependencies
        script: |
          echo "No dependencies to install"
      - name: Build iOS app
        script: |
          xcodebuild -scheme $APP_NAME -sdk iphoneos -configuration Release archive -archivePath build/$APP_NAME.xcarchive
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive -archivePath build/$APP_NAME.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build
    artifacts:
      - build/*.ipa
